drop table if exists category cascade;
drop table if exists area cascade;
drop table if exists area_image cascade;
drop table if exists area_link cascade;
drop table if exists booth cascade;
drop table if exists booth_image cascade;
drop table if exists booth_link cascade;
drop table if exists menu cascade;
drop table if exists post cascade;
drop table if exists post_image cascade;
drop table if exists post_link cascade;
drop table if exists stop_time cascade;
drop table if exists timeslot cascade;

create table category (id bigint AUTO_INCREMENT, name varchar(255) not null, icon varchar(255) not null, color varchar(255) not null, created_at timestamp(6) not null, modified_at timestamp(6) not null, primary key (id));
create table area (id bigint AUTO_INCREMENT, name varchar(255) not null, summary varchar(255), description text not null, x integer, y integer, open timestamp(6), close timestamp(6), created_at timestamp(6) not null, modified_at timestamp(6) not null, primary key (id));
create table area_image (area_id bigint not null, src varchar(255));
create table area_link (area_id bigint not null, label varchar(255), href varchar(255));
create table booth (id bigint AUTO_INCREMENT, area_id bigint, category_id bigint not null, dtype varchar(31) not null, name varchar(255) not null, summary varchar(255), description text not null, x integer, y integer, open timestamp(6), close timestamp(6), type enum ('ALL','ENTRY','EXIT'), created_at timestamp(6) not null, modified_at timestamp(6) not null, primary key (id));
create table booth_image (booth_id bigint not null, src varchar(255));
create table booth_link (booth_id bigint not null, label varchar(255), href varchar(255));
create table menu (id bigint AUTO_INCREMENT, store_id bigint not null, image varchar(255) not null, name varchar(255) not null, price bigint not null, created_at timestamp(6) not null, modified_at timestamp(6) not null, primary key (id));
create table post (id bigint AUTO_INCREMENT, title varchar(255) not null, content text not null, created_at timestamp(6) not null, modified_at timestamp(6) not null, primary key (id));
create table post_image (post_id bigint not null, src varchar(255));
create table post_link (post_id bigint not null, label varchar(255), href varchar(255));
create table stop_time (stop_id bigint not null, time time(6));
create table timeslot (id bigint AUTO_INCREMENT, name varchar(255) not null, start_time timestamp(6) not null, end_time timestamp(6) not null, href varchar(255), created_at timestamp(6) not null, modified_at timestamp(6) not null, primary key (id));

alter table area_image add constraint FKh5t1438yoh9qdbrp5rhup1e2r foreign key (area_id) references area(id);
alter table area_link add constraint FKkpk95weftxx5ninyauarxq6er foreign key (area_id) references area(id);
alter table booth add constraint FK81p86gtlidlj9b4wyp66x1dgc foreign key (area_id) references area(id);
alter table booth add constraint FK2rrpioqdbuew45fwlxu8yhyev foreign key (category_id) references category(id);
alter table booth_image add constraint FK2owvids78jsimets3o73xqo9p foreign key (booth_id) references booth(id);
alter table booth_link add constraint FKofy8vjjy9jaubd42vikovhlww foreign key (booth_id) references booth(id);
alter table menu add constraint FK79sgcs9it1tx77sxxg1y4p808 foreign key (store_id) references booth(id);
alter table post_image add constraint FKsip7qv57jw2fw50g97t16nrjr foreign key (post_id) references post(id);
alter table post_link add constraint FK5wva6r3xensp9n1x9llbw3wtv foreign key (post_id) references post(id);
alter table stop_time add constraint FKglo6p7gvk63smq8rsej4atkwu foreign key (stop_id) references booth(id);
